### ISSUE TITLE
一场注定会分手的恋爱

### ISSUE THREAD

**Issue by lmk123** [lmk123/blog#13]
小 C 答应做我女朋友了。

可是我并没有很开心。

第一次告白的时候我失败了。这早在我的预料之中。

“我是不会答应的。”小 C 背对着我说。

“我只是想要说出我心里的话，以免以后回想起来觉得遗憾，并没有奢求你答应我，所以你不要在意。”

一阵沉默之后，小 C 突然问：“你想抱抱我吗？”

当她这么问的时候，她的心里是怎么想的呢？我没有细想，只是迫不及待的拥了上去，还得寸进尺的吻了她。她没有拒绝。

“我知道你喜欢我，也知道你一直都对我很好。但是，我就是对你没感觉。你吻我的时候，我一点感觉都没有。”

我抱着她，没有说话。

那段时间，小 C 刚毕业，想来 A 城找工作（她真的爱死这个城市了），正好我在 A 城上班，于是就去接她。上面的告白就是在她来的第一天晚上发生的。

表明自己的心意之后，我发现她对我的态度开始一点点的转变。一起外出的时候她会突然搂住我的胳膊，我表面觉得平静，心里却翻江倒海，然而她的温度我还没体验够的时候，她却把手抽开了。

“我只是喜欢这样搂着男生而已，并不是因为是你才搂的，你不要误会。”

我“哦”了一声，怅然若失。

小 C 身边绝不缺想要请她吃饭的男孩子，这我是知道的。她活泼、调皮，手机里的微信消息从不间断，经常回几条消息之后就跟我说哪个男孩子又要约她出去玩。

这种时候我是什么心情呢？就好像看见柜台里我喜欢的玩具被别人买走了一样。

然而 小 C 并不属于任何人。

和她在一起的时候我常常想，我到底是她的什么人？我看着她笑着跟我说话的样子，想要从她的表情里捕捉到一点蛛丝马迹。她明亮的眼神、上翘的嘴角都散发着“她喜欢我”的错觉，然而当我想去牵她的手的时候，却总是抓不住。我想问，却害怕开口。我怕我一旦认真，就连这点亲昵也会输掉。

终于，在一次长吻过后，我还是忍不住问了。

“小 C 啊。”

“嗯？”

“你把我当作你的什么人？”

沉默。

“朋友。可是现在我这么说你也不会信吧。”

当然不会信。

“经过这几天相处，我承认我有那么一点点喜欢你，跟你接吻的时候也慢慢有感觉了。”小 C 平静的说，“但我还是不想做你的女朋友。”

我没有问为什么。

“我们俩本身就是很好的朋友，彼此对对方都太熟悉了。我们就这样在一起不是也很好吗，为什么一定要成情侣呢？”

“因为我不想你跟别的男孩子走得太近。”

“还有一点原因，”小 C 没有回应我上面的回答，“我有很多想要的东西，从小到大我爸妈给我买这些我都习惯了，但是工作之后我肯定不好意思找他们要了。所以我想要男朋友给我买，我也知道你现在跟同龄人比工资算是很高的，但是……”

跟我想要的比起来也只是杯水车薪。我扫了扫她包里那些我不懂的化妆品，在心里帮她补完了这句话。

“我也不想花你的钱，你以后还得用这些钱买房买车，我觉得这样做特对不住你。”

原来这才是实话。

原来这才是实话。

原来这才是实话。

“你别这样，我不想看到你这个样子。”小 C 凑过来，送上了她的嘴唇。

“也就是说你以后会找一个有钱的男朋友，即使你并不喜欢他，只要他能跟你买你想要的东西就好？”

“喜欢不喜欢什么的，反正也不重要了。你是不是觉得我特拜金？”

如果换作是其他人，肯定就会回答“是”了吧？可偏偏我是那么懂她。她太聪明了，“反正时间长了就会厌倦的吧。”她总是这样评价“感情”；她也并不是拜金，只是这样的生活已经成了她的习惯。

我没法满足她。我空有一片真心，却给不了她想要的物质生活。我真的觉得内心深处有一块地方抽动了一下。

“我真觉得你很有前途的，我之所以喜欢跟你一起玩就是觉得你有能力，做事靠谱，再过个几年你一定会成为一个有钱的人……”

我打断了她：“也就是说，我应该在几年后再遇见你才对？”

“也就是说，时间不对。”

我真的没话可说了。我低着头发呆，可是心里却一片空白。果然我就不该开口问的。

小 C 抱住了我。

“做我女朋友吧。”我下定了决心。“我知道以后我们一定会分手。可我还是想跟你在一起。"

“我不会跟任何人说起这件事，你也不需要跟任何人提起。公共场合我不会再去想要牵你的手，一切表现的就跟普通朋友一样。你还是可以去物色你未来的男朋友，我不会干涉你。”

我感觉到小 C 抬起头正看着我。我尽量不去想像她此刻的表情。

“如果以后你想跟我分手，那一定是我自己没有优秀到能留住你。”

就这样，小 C 答应做我的女朋友了。

可是我并没有很开心。

小 C 是怀着怎样的心情答应我的呢？“跟我在一起，我一定会把你调教的好好的！”小 C 开心的表情不像是假的，但随即就黯淡了。“反正都是帮别人调教的，就当我回报你吧。”

以后我应该做些什么来留住她？在她找到未来的男朋友之前，我能优秀到让她留下来吗？我看着怀里熟睡的小 C ，脑海里不断重复这些问题。我想像着“未来的男朋友”居高临下的看着我，将小 C 从我身边带走，嘴角带着轻蔑的表情。

我知道，我要开始一场跟时间的赛跑了。

**Comment by cyio** [comment]
第一人称，还以为写的是真事
看到“小说”的标签，原来是创作
又移除了“小说”，成悬疑了

**Comment by lmk123** [comment]
你理解的很透彻 :)
