### ISSUE TITLE
我开通了微信公众号，欢迎关注 DoneIsBetterThanPerfect

### ISSUE THREAD

**Issue by lmk123** [lmk123/blog#77]
迫于 GitHub 越来越难访问了，我开通了微信公众号，目前正在慢慢的将博客的内容搬运过去，未来文章会优先发布在公众号里，然后同步在 GitHub 中，欢迎关注：

<img width="390" src="https://user-images.githubusercontent.com/5035625/78118873-2ec7e980-743a-11ea-8803-a9a4265f321a.jpg">

如果看不到图片，可以在微信里搜索 `DoneIsBetterThenPerfect` 关注。

**Comment by laiyongxin** [comment]
你的公众号微信都收索不到
